### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by miftah1991** [miftah1991/Pokemon#21]
There are two members in our team

Miftah @miftah1991 
Francisco @franciscoPonceDev 

https://github.com/miftah1991/Pokemon/projects/4

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @miftah1991 and @franciscoPonceDev,

Good job so far!
✔️ Kanban board is well set up
✔️ Correct number of columns
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly decide who is **Student A** and **Student B** and ensure that all your tasks are assigned to the appropriate student (see image for example)

  ![andre-assigned](https://user-images.githubusercontent.com/36542986/157092883-1be7ddcc-cf59-4747-a9e9-dd4fde17703b.jpg)

- [ ] Since there are only 2 students on the project, kindly remove all tasks pertaining to **Student C**

- [ ] The following tasks have duplicates on your board. Kindly remove the duplicates
  - [[0.5pt] Find external API - group task](https://github.com/miftah1991/KanbanBoard/issues/40)
  - [[1pt] Choose assets - group task](https://github.com/miftah1991/KanbanBoard/issues/39)
  - [[0.5pt] Set up the project with Webpack and Jest- group task](https://github.com/miftah1991/KanbanBoard/issues/38)
  - [[0.5pt] Add header - group task](https://github.com/miftah1991/KanbanBoard/issues/37)
  - [[0.5pt] Add footer - group task](https://github.com/miftah1991/KanbanBoard/issues/36)
  - [[4pt] - Display list of items on the Homepage - Student A](https://github.com/miftah1991/KanbanBoard/issues/35)
  - [[4pt] -Display Comments pop up with selected item's details - Student B](https://github.com/miftah1991/KanbanBoard/issues/34)
  - [[4pt] - Display number of likes for each item on the Homepage - Student A](https://github.com/miftah1991/KanbanBoard/issues/32)
  - [[3pt] - Display comments for a given item on the Comments pop-up - Student B](https://github.com/miftah1991/KanbanBoard/issues/31)
  - [[3pt] - Create feature: add new like - Student A](https://github.com/miftah1991/KanbanBoard/issues/29)
  - [[4pt] - Create feature: add new comment - Student B](https://github.com/miftah1991/KanbanBoard/issues/28)
  - [[3pt] - Add all items counter on the Homepage - Student A](https://github.com/miftah1991/KanbanBoard/issues/26)
  - [[3pt] - Add comments counter - Student B](https://github.com/miftah1991/KanbanBoard/issues/25)
  - [[3pt] - Add tests for items counter - Student A](https://github.com/miftah1991/KanbanBoard/issues/23)
  - [[3pt] - Add tests for comments counter - Student B](https://github.com/miftah1991/KanbanBoard/issues/22)

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by miftah1991** [comment]
@TedLivist 

Thanks for your review,
Sorry for the inconvenience we have set up the kanban on the demo project and then we set up the project on the Live project and mistakenly we have submitted the demo project link in the issue, in our Pokemon Project the Kanban is already setup as per the requirements.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @miftah1991 and @franciscoPonceDev,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
